version: '3.8'

services:
  aerospike:
    image: aerospike/aerospike-server
    ports:
      - "3003:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - ./data/aerospike:/opt/aerospike/data
      - ./config/aerospike:/etc/aerospike:rw
    environment:
      - NAMESPACE=memepool
    healthcheck:
      test: ["CMD", "asinfo", "-v", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - memepool-net

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - AEROSPIKE_HOST=aerospike
      - AEROSPIKE_PORT=3000
      - AEROSPIKE_NAMESPACE=memepool
    depends_on:
      aerospike:
        condition: service_healthy
    networks:
      - memepool-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

volumes:
  aerospike-data:

networks:
  memepool-net:
    driver: bridge 