version: '3.8'

services:
  ai-video:
    build: .
    ports:
      - "8001:8001"  # HTTP
      - "50051:50051" # gRPC
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 