version: '3.8'

services:
  ai-video:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # HTTP
      - "50051:50051" # gRPC
    volumes:
      - ./app:/app
      - model-cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 16G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - USE_CPU=1
    restart: unless-stopped

volumes:
  model-cache:
    name: ai-video-model-cache 