services:
  ai-video:
    build: 
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8001:8001"  # HTTP
      - "50051:50051" # gRPC
    volumes:
      - ./models:/app/models
    environment:
      - CUDA_VISIBLE_DEVICES=  # Disable CUDA
      - USE_CPU=1 