services:
  ai-video:
    build: 
      context: .
      dockerfile: Dockerfile.amd
    ports:
      - "8001:8001"  # HTTP
      - "50051:50051" # gRPC
    volumes:
      - ./models:/app/models
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - ROCR_VISIBLE_DEVICES=0 