version: '3.8'

services:
  ai-video:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8001:8001"  # HTTP
      - "50051:50051" # gRPC
    volumes:
      - .:/app
      - model-cache:/root/.cache/huggingface
    environment:
      - CUDA_VISIBLE_DEVICES=  # Disable CUDA
      - USE_CPU=1
    deploy:
      resources:
        limits:
          memory: 16G
    restart: unless-stopped

volumes:
  model-cache:
    name: ai-video-model-cache 