# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\"J\n\x0cVideoRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0b\n\x03\x66ps\x18\x02 \x01(\r\x12\x0e\n\x06\x66rames\x18\x03 \x01(\r\x12\x0e\n\x06motion\x18\x04 \x01(\x02\"@\n\rVideoResponse\x12\r\n\x05video\x18\x01 \x01(\x0c\x12 \n\x08metadata\x18\x02 \x01(\x0b\x32\x0e.VideoMetadata\"Q\n\rVideoMetadata\x12\x15\n\rmodel_version\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02\x12\x17\n\x0fprocessing_time\x18\x03 \x01(\x02\x32\x42\n\x0eVideoGenerator\x12\x30\n\rGenerateVideo\x12\r.VideoRequest\x1a\x0e.VideoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOREQUEST']._serialized_start=15
  _globals['_VIDEOREQUEST']._serialized_end=89
  _globals['_VIDEORESPONSE']._serialized_start=91
  _globals['_VIDEORESPONSE']._serialized_end=155
  _globals['_VIDEOMETADATA']._serialized_start=157
  _globals['_VIDEOMETADATA']._serialized_end=238
  _globals['_VIDEOGENERATOR']._serialized_start=240
  _globals['_VIDEOGENERATOR']._serialized_end=306
# @@protoc_insertion_point(module_scope)
